"""empty message

Revision ID: 7e39777f002d
Revises: b39b9a25c74a
Create Date: 2025-06-23 11:11:51.795670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e39777f002d'
down_revision = 'b39b9a25c74a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_documents_id'), ['id'])

    with op.batch_alter_table('statistics', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_statistics_id'), ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_id'), ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_id'), type_='unique')

    with op.batch_alter_table('statistics', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_statistics_id'), type_='unique')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_documents_id'), type_='unique')

    # ### end Alembic commands ###
