"""added statistic table

Revision ID: d8f951509de1
Revises: 3dd760bfca39
Create Date: 2025-01-03 14:36:39.241287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8f951509de1'
down_revision = '3dd760bfca39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statistics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('word_count', sa.INTEGER(), nullable=False),
    sa.Column('tags', sa.TEXT(), nullable=False),
    sa.Column('sentiment', sa.String(length=500), nullable=False),
    sa.Column('asset', sa.TEXT(), nullable=False),
    sa.Column('document_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_statistics_document_id_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_statistics')),
    sa.UniqueConstraint('id', name=op.f('uq_statistics_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statistics')
    # ### end Alembic commands ###
